version: '3.7'

networks:
  loki:

services:

  myapp:
    image: supersloy/devops:latest
    container_name: myapp
    volumes:
      - /data:/data
    ports:
      - "80:5000"
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
        max-size: 10m
    deploy:
      resources:
        limits:
          memory: 64M

  loki:
    image: grafana/loki:2.0.0
    container_name: monitoring.loki
    expose:
      - 3100
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - loki
    deploy:
      resources:
        limits:
          memory: 64M

  promtail:
    image: grafana/promtail:2.0.0
    container_name: monitoring.promtail
    expose:
      - 9080
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers/:/var/lib/docker/containers
      - ./docker-config.yml:/etc/promtail/docker-config.yml
    command: -config.file=/etc/promtail/docker-config.yml
    restart: unless-stopped
    networks:
      - loki
    deploy:
      resources:
        limits:
          memory: 64M

  grafana:
    image: grafana/grafana:master
    container_name: monitoring.grafana
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - loki
    deploy:
      resources:
        limits:
          memory: 64M

  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring.prometheus
    restart: unless-stopped
    expose: 
      - 9090
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - loki
    deploy:
      resources:
        limits:
          memory: 64M