apiVersion: v1
kind: Service
metadata:
  name: clock-service
  labels:
    app: clock
spec:
  type: LoadBalancer
  ports:
    - port: 10101
      nodePort: 32000
      protocol: TCP
  selector:
    app: clock